# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

2.3.5


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
z=np.zeros((1,2))
print(z.nbytes)


16


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)


Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
z=np.arange(10,50)
z1=z[::-1]
print(z1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
z=np.array([1,2,0,0,4,0])
index=np.nonzero(z)
print(index)



(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
matrix=np.random.random((3,3,3))


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
matrix=np.random.random((10,10))
print("min:",matrix.min())
print("max:",matrix.max())

min: 0.0057536938890703215
max: 0.9987579662802859


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
matrix=np.random.random(30)
mean=matrix.mean()

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
z=np.ones((5,5))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np

z = np.ones((3,3))
z2 = np.pad(z, pad_width=1, mode='constant', constant_values=0)

print(z)
print(z2)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
z=np.zeros((8,8),dtype=int)

z[1::2, ::2]=1
z[::2, 1::2]=1

print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [25]:
idx=np.unravel_index(100,(6,7,8))
print(idx)

(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np

pattern = np.array([[0, 1],
                    [1, 0]])

z = np.tile(pattern, (4, 4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
Z=np.random.random((5,5))
Z_norm = (Z - Z.min()) / (Z.max() - Z.min())
print(Z_norm)

[[0.38321096 0.22265557 0.09095486 0.         0.70700239]
 [0.33414442 0.91635511 0.26271968 0.27870389 0.03783994]
 [0.04850461 0.07604183 0.94007998 0.4776673  0.29437117]
 [0.10004377 0.69976014 0.55144645 0.3115387  0.47166696]
 [0.60434313 0.57328511 1.         0.26092922 0.14052878]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_dtype = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])

colors = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=color_dtype)
print(colors)
print(colors['r'])

[(255,   0, 0, 255) (  0, 255, 0, 128)]
[255   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
A=np.random.random((5,3))
B=np.random.random((3,2))

c=A @ B
print(c)


[[0.59109146 1.14963848]
 [0.74125426 0.70878497]
 [0.67324145 1.15035444]
 [0.69585589 0.72615341]
 [0.88503736 0.95479315]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
z=np.arange(11)
mask=(z>3) & (z<8)
z[mask] *=-1
print(mask)

[False False False False  True  True  True  True False False False]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [38]:
Z**Z
2<<Z>>2
Z <- Z
1j*Z
Z/1/1


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆)

In [40]:
Z = np.array([-2.3, -1.1, 0.2, 1.7, 3.0])
z_around = np.where(Z > 0, np.ceil(Z), np.floor(Z))
print(z_around)

[-3. -2.  1.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [41]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])

common=np.intersect1d(a,b)
print(common)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [44]:
import numpy as np
old =np.seterr(all='ignore')
np.seterr(**old)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
today=np.datetime64('today','D')
yesterday=today-np.timedelta64(1,'D')
Tomorrow=today+np.timedelta64(1,'D')
print("Today:",today)
print("Yesterday:",yesterday)
print("Tomorrow:",Tomorrow)


Today: 2025-11-24
Yesterday: 2025-11-23
Tomorrow: 2025-11-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
dates= np.arange('2016-07-01', '2016-07-02',
               dtype='datetime64[D]')
print(dates)

['2016-07-01']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [48]:
a=np.random.random((3,3))
b=np.random.random((3,3))

np.add(a,b,out=b)
np.multiply(a,-0.5,out=a)
np.multiply(a,b,out=a)
print(a)

[[-0.17386156 -0.08786374 -0.10714278]
 [-0.29216466 -0.04397012 -0.02856722]
 [-0.03766858 -0.08475323 -0.32310897]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [50]:
z=np.random.uniform(0,10,10)
m1=np.floor(z)
m2=z.astype(int)
m3=np.trunc(z)
m4=z//1
print(z)
print(m1,m2, m3, m4)

[8.58509131 4.25610958 6.17082869 2.02202647 2.61251055 2.78374335
 4.171676   2.6327429  6.57934725 9.06775055]
[8. 4. 6. 2. 2. 2. 4. 2. 6. 9.] [8 4 6 2 2 2 4 2 6 9] [8. 4. 6. 2. 2. 2. 4. 2. 6. 9.] [8. 4. 6. 2. 2. 2. 4. 2. 6. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [52]:
z=np.tile(np.arange(5),(5,1))
print(z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [53]:
def gen():
    for i in range(10):
        yield i
    
Z= np.fromiter(gen(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [54]:
z=np.linspace(0,1,12)[1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [55]:
z=np.random.random(10)
z.sort()
print(z)

[0.05454358 0.15771898 0.21079538 0.2307227  0.27276014 0.55012478
 0.67324825 0.79401283 0.79985133 0.90386279]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [56]:
z=np.arange(10)
print(sum(z))

45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [57]:
a=np.random.random((3,3))
b=np.random.random((3,3))
print(np.array_equal(a,b))


False


#### 43. Make an array immutable (read-only) (★★☆)

In [59]:
z=np.zeros(10)
z.setflags(write=False)
print(z.flags.writeable)

False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [60]:
z=np.random.random((10,2))
x=z[:,0]
y=z[:,1]

r=np.sqrt(x**2 + y**2)
thetha=np.arctan2(y,x)

polar=np.column_stack((r,thetha))
print(polar)

[[1.00531796 0.95819706]
 [0.99335405 0.44347767]
 [0.97236595 0.22460117]
 [0.7135756  0.59754594]
 [0.76622609 0.33806702]
 [1.06390139 1.03079623]
 [0.68999499 0.20043672]
 [0.68065245 0.86898023]
 [0.91610408 0.45101163]
 [0.9230641  0.68096711]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [61]:
dtype = [('x', float), ('y', float)]

x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)

X, Y = np.meshgrid(x, y)

Z = np.zeros(X.size, dtype=dtype)
Z['x'] = X.ravel()
Z['y'] = Y.ravel()

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [63]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
c=1.0/(X[:, None] - Y[None, :])
print(c)

[[[        inf  4.          2.          1.33333333  1.        ]
  [-4.                 inf  4.          2.          1.33333333]
  [-2.         -4.                 inf  4.          2.        ]
  [-1.33333333 -2.         -4.                 inf  4.        ]
  [-1.         -1.33333333 -2.         -4.                 inf]]

 [[        inf  4.          2.          1.33333333  1.        ]
  [-4.                 inf  4.          2.          1.33333333]
  [-2.         -4.                 inf  4.          2.        ]
  [-1.33333333 -2.         -4.                 inf  4.        ]
  [-1.         -1.33333333 -2.         -4.                 inf]]

 [[        inf  4.          2.          1.33333333  1.        ]
  [-4.                 inf  4.          2.          1.33333333]
  [-2.         -4.                 inf  4.          2.        ]
  [-1.33333333 -2.         -4.                 inf  4.        ]
  [-1.         -1.33333333 -2.         -4.                 inf]]

 [[        inf  4.          2.    

/var/folders/ql/r6qdkzvd0l15h7n2wbmfyy6w0000gn/T/ipykernel_50763/2911263760.py:3: RuntimeWarning: divide by zero encountered in divide
  c=1.0/(X[:, None] - Y[None, :])


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
for t in [np.int8,np.int16,np.int32,np.int64]:
    print(t, np.iinfo(t).min, np.iinfo(t).max)
    
for t in [np.float16,np.float32,np.float64]:
    print(t, np.finfo(t).min, np.finfo(t).max)


#### 49. How to print all the values of an array? (★★☆)

In [64]:
np.set_printoptions(threshold=np.inf)
Z = np.arange(1000)
print(Z)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
z=np.array([0.2, 1.7, 2.9, 3.1, 4.8])
v = 3.0
idx = np.abs(Z - v).argmin()
closest = Z[idx]

print("closest:", closest)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [66]:
pixel_dtype = np.dtype([
    ('x', float),
    ('y', float),
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8)
])

pixels =np.array([
    (0.0, 0.0, 255,   0,   0),
    (1.0, 0.5,   0, 255,   0),
    (0.5, 1.0,   0,   0, 255),
],dtype=pixel_dtype)

print(pixels)
print(pixels['x'])
print(pixels['r'])

[(0. , 0. , 255,   0,   0) (1. , 0.5,   0, 255,   0)
 (0.5, 1. ,   0,   0, 255)]
[0.  1.  0.5]
[255   0   0]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((100, 2))

diffs = Z[1:] - Z[:-1]
dists = np.sqrt((diffs ** 2).sum(axis=1))

print(dists)
print(dists.shape)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)

Z_int = Z.view(np.int32)

print(Z)
print(Z_int)
print(Z_int.dtype)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
z=np.genfromtxt('data.txt', delimiter=',',dtype=float)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z=np.arange(9).reshape((3,3))

for idx, value in np.ndenumerate(Z):
    print(idx, value)
    

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
n = 64
sigma = 10.0

x = np.linspace(-n/2, n/2, n)
y = np.linspace(-n/2, n/2, n)
X, Y = np.meshgrid(x, y)

G = np.exp(-(X**2 + Y**2) / (2 * sigma**2))

print(G.shape)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n,m=10,10
p=15

Z = np.zeros((n, m), dtype=int)

indices = np.random.choice(n * m, p, replace=False)
Z[np.unravel_index(indices, (n, m))] = 1

print(Z)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
asdasdasdas

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)